import * as React from 'react';
import { ImagePreview } from '../../src/components/ImagePreview';
import * as ImageService from '../../src/services/ImageService';
import { render } from '@testing-library/react';

jest.mock('../../src/services/ImageService');

describe('ImagePreview', () => {
  const mockedImageService = ImageService as jest.Mocked<typeof ImageService>;

  it('should not display autogenerated filename text', async () => {
    const rendered = render(<ImagePreview src='http://localhost:5174/1680037067465-pineapple.jpeg'/>)

    expect(await rendered.findByText('pineapple.jpeg')).toBeInTheDocument();
    expect(rendered.queryByText('1680037067465-pineapple.jpeg')).not.toBeInTheDocument();
  });
});